# Generated by Django 3.0.8 on 2020-07-21 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professor', models.CharField(max_length=50)),
                ('rq_year', models.ImageField(upload_to='')),
                ('rq_semester', models.ImageField(upload_to='')),
                ('department', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=50)),
                ('instruction_number', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('credit', models.ImageField(upload_to='')),
                ('time', models.IntegerField()),
            ],
        ),
    ]
